spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pg
    username: pg
    password: pg
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    sql:
      init:
        mode: always

